import Head from 'next/head'
import styles from '../styles/Layout.module.css'
import Sidebar from './sidebar'
const Layout = ({ children }) => {
    return (
        <>
            <Head>
                <title>{process.env.title}</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Sidebar />

            <div id="main-container" className={styles.container}>
                <main className={styles.main}>{children}</main>

                <footer className={styles.footer}>
                    <a
                        href="https://github.com/KaizukiZero"
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        &copy; Copyright 2021 Kaizuki-Zero
                    </a>
                </footer>
            </div>
        </>
    )
}

export default Layout
