import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

var one = 1;

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>{process.env.title}</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}></main>

            <footer className={styles.footer}>
                <a
                    href="https://github.com/KaizukiZero"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    &copy; Copyright 2021 Kaizuki-Zero
                </a>
            </footer>
        </div>
    )
}
